### PR TITLE
Separate out config for temp and perm container

### PR DESCRIPTION
**Pull request by samiyaakhtar**

### CODE REVIEW

**Comment by mtarng** [comment]
I know we currently have these configured in our function app settings:
```
"SOURCE_CONTAINER_NAME": "tempcont",
    "DESTINATION_CONTAINER_NAME": "permcont",
```
should double check these are consistent, right?

**Comment by samiyaakhtar** [comment]
@mtarng ideally yes, but the cli config can’t access the function config settings right? Didn’t know how to check if they’re unequal and throw error.

**Comment by andrebriggs** [comment]
> @mtarng ideally yes, but the cli config can’t access the function config settings right? Didn’t know how to check if they’re unequal and throw error.

This brings up the question of how got we want the experience to be from setting up the deployment config file to setting up the CLI config file. Think this PR is a stop gap until we decide if we want to create a 3rd blob container. Most likely will need to. There are other training artifacts we will want to store in blob storage. For now I'm fine with using the "permanent" image store as the model store.

**Review by andrebriggs — APPROVED** [review]

**Comment by mtarng** [comment]
I know we can call something like `func azure functionapp fetch-app-settings cmhack-func-mtarng` but it's all encrypted

**Comment by samiyaakhtar** [comment]
Closing it as we'll continue to use perm store as model store, for now

**Pull request merged**
